server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Set the logging level
logging.level.org.springframework.web=DEBUG
logging.level.com.wkrzywiec.medium=INFO

# Log to a specific file
logging.file.name=/var/log/kanban-app.log

# Set the log file size limit (optional)
logging.file.max-size=10MB

# Archive old log files (optional)
logging.file.max-history=30
